error_txt='';
try
input1='kk7v1v6ph1mfsgn5j0hc44ken3IRMAtrain.csv';
input2='';
input3='kk7v1v6ph1mfsgn5j0hc44ken3IRMAlabels.csv';
input4=5;
input5=2;
input6=10;
input7='ELM';
input8=5;
input9=50;
input10=['T','S','U'];
input11=5;
addpath('GRNNminer')
addpath('GRNNminer/data')
addpath('GRNNminer/data/IRMA')
addpath('GRNNminer/code')
addpath('GRNNminer/out')
addpath('DatosCargados')
addpath('LabelCargadas')
addpath('TargetCargadas')
addpath('DatosSimulados')
addpath('LabelPredeterminadas')
[output1,output2]=mainWeb(input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11);
disp('g')
quit;
end

